name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: install homebrew
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: install automake
      - run: brew install automake
      - name: install libtool
      - run: brew install libtool
      - name: clone cppunit
      - run: git clone git://anongit.freedesktop.org/git/libreoffice/cppunit/
      - name: cd cppunit
      - run: cd cppunit
      - name: autogen.sh
      - run: ./autogen.sh
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make install
        run: make install